### ISSUE TITLE
Suggestion: implement a ServerStart webhook

### ISSUE THREAD

**Issue by litokey** [Alderon-Games/pot-community-servers#44]
[12:31 AM] MENIX: Would it be possible to implement a ServerStart webhook? Triggering when the server begins booting up/finished booting something (whenever fastest possible I guess)

Perhaps just including:

serverName: BlaBla
startedAt: date.timeNow()  (or whatever you use)

- as entry in the Json thing it passes to hook

Reason: monitoring uptime/crashes/bypass a message to Discord that the server is coming up after a restart (server status info)

**Comment by menix1337** [comment]
With the introduction of Source Query - this feature would still be very loved have, as source query doesn't exactly cover this.
(Just due to lost connections to query can happen, and i would not want that to be misunderstood for a restart)

So this Webhook suggestion would still be very very very **very** loved.

**Comment by AlderonEmu** [comment]
The ServerStart webhook has been fixed in a future patch!
